name: Tests

on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16.19.0'

      - name: Cache yarn node_modules
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install

      - name: Typescript type check
        run: yarn run ts-check

      - name: Lint check
        run: yarn run lint

      #- name: Tests
      #  run: yarn run test:ci

      - name: Build test
        run: yarn run build

      - name: Pull request to main
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main'
          pr_label: 'automerge'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull request to dev
        if: ${{ github.ref != 'refs/heads/dev' && github.ref != 'refs/heads/main' }}
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'dev'
          pr_label: 'automerge'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Slack Report
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ":robot_face:"
          SLACK_USERNAME: 'Verza Bot'
          SLACK_CHANNEL: dev-log-public
          SLACK_COLOR: ${{ job.status }}
          SLACK_TITLE: ${{ github.repository }}
          SLACK_MESSAGE: ':rocket: ${{ job.status }}'
          SLACK_WEBHOOK: ${{ secrets.DEV_LOG_SLACK_WEBHOOK_PUBLIC }}


